name: Build and deploy - DEV

on:
    push:
        branches:
            - develop

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: Dev
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install node
              uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: Install dependecies
              run: npm install

            - name: Create development build
              run: npm run build
              env:
                  REACT_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
                  REACT_APP_GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
                  REACT_APP_MAP_THEME_URL: mapbox://styles/healthmap/cknr3ycvx03i917nw4gk1um66
                  REACT_APP_SHEETS_ID: 15-2lbrYHHL0zFYc9kzS7_m6CCV5BkBCUeg9ifTHbRos
                  REACT_APP_SHEET_NAME: Variants
                  REACT_APP_DATA_PORTAL_URL: https://dev-data.covid-19.global.health
                  REACT_APP_COUNTRY_VIEW_DATA_URL: https://covid-19-aggregates-dev.s3.eu-central-1.amazonaws.com/country/latest.json
                  REACT_APP_VARIANT_DATA_URL: https://covid-19-aggregates-dev.s3.eu-central-1.amazonaws.com/variant-reporting-data.json
                  REACT_APP_REGIONAL_VIEW_DATA_URL: https://covid-19-aggregates-dev.s3.eu-central-1.amazonaws.com/regional/latest.json

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-2

            - name: Deploy to AWS S3
              run: aws s3 sync ./build s3://dev-react-map.covid-19.global.health --delete
